### ISSUE TITLE
Gebeurtenis bgrSSVSAMEN en bgrSSVSPLITS hebben dezelfde code in Geo-BAG berichtenverkeer

### ISSUE THREAD

**Issue by adbgnm** [Geonovum/GeoBAG#11]
Twee gebeurtenissen hebben dezelfde code in het Geo-BAG berichtenverkeer.

bgrSSVSAMEN en bgrSSVSPLITS zijn in Geo-BAG beide BGR-SSV.

bgrSSVSAMEN_Lk03	BGR-SSV	Samenvoegen verblijfsobjecten*
bgrSSVSPLITS_Lk03	        BGR-SSV	Splitsen verblijfsobjecten*

**Comment by adbgnm** [comment]
Oplossingsrichting / voorstel: 
Samenvoegen aanpassen naar code 'SMV' en Splitsen aanpassen naar 'code' SPL.

**Comment by adbgnm** [comment]
Gebeurteniscode moet eigenlijk aangepast worden naar BGR-SSVSPLITS en BGRSSVSAMEN cf. Processenhandboek BAG.

Opgelost in https://github.com/Geonovum/GeoBAG/commit/9d069736962110dbd44e940fc2db2cb6ff419e37

**Comment by grivy** [comment]
Aanpassing is nog niet doorgevoerd in de RDF:
GeoBAG/waardelijst/1.0.1-concept/codeList_Gebeurtenis.rdf
