### ISSUE TITLE
Exact propertie 

### ISSUE THREAD

**Issue by MarcPulles** [Geonovum/GeoBAG#20]
Wat is het doel van de Exact proportie in het berichtenverkeer?
Wij hebben deze geïmplementeerd vanuit GeoBgt en standaard op true gezet. Echter in de eerste aangeleverde testbestanden komt Exact helemaal niet voor. Wat wordt verwacht door BAG en wat wordt verzonden door BAG omtrent deze propertie? Is de waarde true (default) hetzelfde als niet meegeven?

**Comment by adbgnm** [comment]
StUF:exact is een optioneel element om aan te geven of de waarde exact is of niet exact. In de StUF standaard staat o.a. :

_Wanneer het attribute StUF:exact ontbreekt of de waarde true heeft, dan voldoen alleen objecten,
waarbij de waarde voor het selectiecriterium exact overeenkomt met de gespecificeerde waarde. Dit mechanisme is bijvoorbeeld nuttig, als je een persoon zoekt maar niet weet of hij Jansen heet of Janssen. Als voor het element <geslachtsnaam> binnen het element <gelijk> Jans en het attribute StUF:exact=”false” wordt gespecificeerd, dan worden zowel de Jansen’s als de Janssen’s teruggeven. _ 

Standaard op true zetten als default is niet persé nodig; weglaten mag ook.

**Comment by adbgnm** [comment]
De vraag+antwoord is opgenomen in de Wiki: https://github.com/Geonovum/GeoBAG/wiki/Wat-is-het-doel-van-StUF:exact%3F. Het issue kan hiermee gesloten worden.
