### ISSUE TITLE
Kennisgevingen van invloed op BGT

### ISSUE THREAD

**Issue by adbgnm** [Geonovum/GeoBAG#34]
Onderstaande gebeurtenissen kunnen ook relevant zijn voor de BGT, maar zijn nog niet vermeld in de Geo-BAG standaard:
•	bagBN - BAG-BN - Benoemen nevenadres – Kan invloed hebben op BGT NAR
•	bagFGO - BAG-FGO - Formalisering geconstateerd object - Kan nieuw vbo bevatten en dus invloed hebben op BGT NAR
•	bagIN - BAG-IN - Intrekken adres – Mogelijk invloed op BGT NAR wijziging/verwijdering
•	bgrBIG - BGR-BIG - Beschikbaar komen ingemeten geometrie – Invloed op BGT geometrie (Geo hoeft niet de enige bron van ingemeten data te zijn)

Verder zijn er deze twee gebeurtenissen waarvan niet helemaal zeker is of deze inderdaad geen invloed kunnen hebben op de BGT.
•	bagHER - BAG-HER - Gemeentelijke herindeling/grenscorrectie (staat niet in proces handboek)
•	bgrVB - BGR-VB - Melding verandering voortgang bouw/sloop (staat niet in proces handboek)
•	braHOB - BRA-HOB - Hernoemen openbare ruimte buurgemeente
•	braHWP - BRA-HWP - Hernoemen woonplaats
•	braIWP - BRA-IWP - Intrekken woonplaats

**Comment by RBDnkr** [comment]
Vanuit Vicrea hebben wij nog de volgende opmerkingen.

- BGR-KVO - Kleine verbouwing object --> Is nu A (Toevoegen BGT Pand als planinformatie), zou D (Wijzigen geometrie BGT Pand) moeten zijn.
- BGR-VBI - Verlenen bouwvergunning ingrijpend --> Is nu A (Toevoegen BGT Pand als planinformatie), zou ook D (Wijzigen geometrie BGT Pand) kunnen zijn. Kan daarnaast ook E (Wijzigen nummeraanduidingreeks van BGT Pand) zijn op het moment dat er ook nieuwe VBO's ontstaan.
- BGR-VOCDEEL - Gedeeltelijk verdwijnen objecten door calamiteiten --> Is nu E,F. Zou volgens ons aanleiding tot geometrieverzoek moeten zijn (status in BAG wordt 'in gebruik (niet ingemeten)'). BGT-mutatie moet dan D (Wijzigen geometrie BGT Pand) zijn.
- BAG-IO - In onderzoek plaatsen. Dit kan gebeuren omdat er getwijfeld wordt aan de juistheid van de geometrie. In dat geval kan dit leiden tot een geometrieVerzoek naar Geo.

Wij twijfelen hoe om te gaan met BAG-BN - Benoemen nevenadres. In hoeverre wordt er met nevenadressen rekening gehouden in de BGT?

**Comment by adbgnm** [comment]
@RBDnkr Nummeraanduidingen van nevenadressen worden in de BGT niet uitgesloten. Dus kan/mag voorkomen. 

Overige opmerkingen zijn verwerkt.

**Comment by adbgnm** [comment]
Opgelost in documentatie. Waardelijst moet nog worden uitgebreid.
