### ISSUE TITLE
Voorbeeldbericht B1_gmlDi01_pand_GEO-COG.xml vulling object versie verkeerd

### ISSUE THREAD

**Issue by OscarDekkerCentric** [Geonovum/GeoBAG#51]
In het voorbeeldbericht B1_gmlDi01_pand_GEO-COG.xml (uit voorbeeldberichten 1.1) heeft het element versie de waarde '1' terwijl het element identificatie het attribuut StUF:noValue="geenWaarde"  heeft.
Als er voor het object nog geen identificatie bekend is zal de versie ook nog niet bekend zijn.

In andere GEO-COG voorbeeld berichten is dit wel correct ingevuld.

**Comment by adbgnm** [comment]
Voorbeeldbestanden aangepast. Bleek voor te komen in:

B1_gmlDi01_pand_GEO-COG.xml
B2_foutDu01_verblijfsobject.xml
Opgelost in voorbeeldset voor 1.1.1

**Comment by adbgnm** [comment]
Opgelost in https://github.com/Geonovum/GeoBAG/milestone/4
